### ISSUE TITLE
Docs at thoth-station.ninja haven't been updated since Nov 15th

### ISSUE THREAD

**Issue by fridex** [thoth-station/nepthys#80]
**Describe the bug**

Documentation available at thoth-station.ninja haven't been updated since Nov 15th.

**To Reproduce**
1. Go to https://thoth-station.ninja/docs/developers/adviser/index.html
2. Scroll down
3. See `documentation was generated on Nov 15, 2021`

**Expected behavior**

Docs should be kept up to date.

**Comment by harshad16** [comment]
checking on this.

**Comment by harshad16** [comment]
These are the warning that seems to be the issue:

**Error 1**:
```
looking for now-outdated files... none found
pickling environment... /home/user/clones/lab/thoth/lab/adviser.py:docstring of thoth.lab.adviser.create_adviser_heatmap:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
WARNING: autodoc: failed to import module 'common' from module 'thoth.lab'; the following exception was raised:
No module named 'thoth.storages.si_bandit'
WARNING: autodoc: failed to import module 'inspection' from module 'thoth.lab'; the following exception was raised:
No module named 'thoth.storages.si_bandit'
WARNING: autodoc: failed to import module 'inspection_report' from module 'thoth.lab'; the following exception was raised:
No module named 'thoth.storages.si_bandit'
WARNING: autodoc: failed to import module 'security' from module 'thoth.lab'; the following exception was raised:
No module named 'thoth.storages.si_bandit'
WARNING: autodoc: failed to import module 'solver' from module 'thoth.lab'; the following exception was raised:
No module named 'thoth.storages.si_bandit'
WARNING: autodoc: failed to import module 'viz' from module 'thoth.lab'; the following exception was raised:
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/lab-rTwmChMB/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/clones/lab/thoth/lab/viz/__init__.py", line 8, in <module>
    from jupyter_require.core import execute_with_requirements
  File "/home/user/.local/share/virtualenvs/lab-rTwmChMB/lib/python3.8/site-packages/jupyter_require/__init__.py", line 34, in <module>
    from .notebook import link_css
  File "/home/user/.local/share/virtualenvs/lab-rTwmChMB/lib/python3.8/site-packages/jupyter_require/notebook.py", line 30, in <module>
    from .core import execute_with_requirements
  File "/home/user/.local/share/virtualenvs/lab-rTwmChMB/lib/python3.8/site-packages/jupyter_require/core.py", line 279, in <module>
    require = RequireJS()
  File "/home/user/.local/share/virtualenvs/lab-rTwmChMB/lib/python3.8/site-packages/jupyter_require/core.py", line 90, in __new__
    raise EnvironmentError(msg)
OSError: Jupyter Require found itself running outside of Jupyter.
```

**Comment by harshad16** [comment]
**Error 2**: 
```
WARNING: autodoc: failed to import module 'update_provide_source_distro' from module 'thoth.investigator'; the following exception was raised:
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/investigator-4wbr7z4W/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/clones/investigator/thoth/investigator/update_provide_source_distro/__init__.py", line 20, in <module>
    from .investigate_update_provide_source_distro import parse_update_provide_source_distro_message
  File "/home/user/clones/investigator/thoth/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py", line 26, in <module>
    from ..common import register_handler
  File "/home/user/clones/investigator/thoth/investigator/common.py", line 32, in <module>
    from .configuration import Configuration
  File "/home/user/clones/investigator/thoth/investigator/configuration.py", line 48, in <module>
    class Configuration:
  File "/home/user/clones/investigator/thoth/investigator/configuration.py", line 52, in Configuration
    THOTH_BACKEND_NAMESPACE = os.environ["THOTH_BACKEND_NAMESPACE"]
  File "/usr/lib64/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'THOTH_BACKEND_NAMESPACE'
```

**Comment by harshad16** [comment]
**Error 3**:
```
[KVirtualenv location: /home/user/.local/share/virtualenvs/kebechet-_898aJn5
Installing dependencies from Pipfile.lock (3fe3ad)...
An error occurred while installing fasttext==0.9.1 --hash=sha256:6ead9c6aafe985472066e27c43e33f581b192befd136a84c3c2e8197e7e05be6 --hash=sha256:f79b3447b1612b9b1ad791d4be97db3fecb97762dba01e6fbec389d0d0874772! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting fasttext==0.9.1
[pipenv.exceptions.InstallError]:   Using cached fasttext-0.9.1.tar.gz (57 kB)
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started
[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'
[pipenv.exceptions.InstallError]: Building wheels for collected packages: fasttext
[pipenv.exceptions.InstallError]:   Building wheel for fasttext (setup.py): started
[pipenv.exceptions.InstallError]:   Building wheel for fasttext (setup.py): finished with status 'error'
[pipenv.exceptions.InstallError]:   Running setup.py clean for fasttext
[pipenv.exceptions.InstallError]: Failed to build fasttext
[pipenv.exceptions.InstallError]: Installing collected packages: fasttext
[pipenv.exceptions.InstallError]:     Running setup.py install for fasttext: started
[pipenv.exceptions.InstallError]:     Running setup.py install for fasttext: finished with status 'error'
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:    command: /home/user/.local/share/virtualenvs/kebec
...
[pipenv.exceptions.InstallError]:     gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
[pipenv.exceptions.InstallError]:     compilation terminated.
[pipenv.exceptions.InstallError]:     Traceback (most recent call last):
[pipenv.exceptions.InstallError]:       File "<string>", line 1, in <module>
[pipenv.exceptions.InstallError]:       File "/tmp/pip-install-e6gaigrv/fasttext_5ef2bef9feac453c9ee1e45e65c18234/setup.py", line 168, in <module>
[pipenv.exceptions.InstallError]:         setup(
[pipenv.exceptions.InstallError]:       File "/home/user/.local/share/virtualenvs/kebechet-_898aJn5/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in setup
[pipenv.exceptions.InstallError]:         return distutils.core.setup(**attrs)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
[pipenv.exceptions.InstallError]:         dist.run_commands()
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
[pipenv.exceptions.InstallError]:         self.run_command(cmd)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
[pipenv.exceptions.InstallError]:         cmd_obj.run()
[pipenv.exceptions.InstallError]:       File "/home/user/.local/share/virtualenvs/kebechet-_898aJn5/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
[pipenv.exceptions.InstallError]:         return orig.install.run(self)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/command/install.py", line 556, in run
[pipenv.exceptions.InstallError]:         self.run_command('build')
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
[pipenv.exceptions.InstallError]:         self.distribution.run_command(command)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
[pipenv.exceptions.InstallError]:         cmd_obj.run()
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/command/build.py", line 135, in run
[pipenv.exceptions.InstallError]:         self.run_command(cmd_name)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/cmd.py", line 313, in run_command
[pipenv.exceptions.InstallError]:         self.distribution.run_command(command)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
[pipenv.exceptions.InstallError]:         cmd_obj.run()
[pipenv.exceptions.InstallError]:       File "/home/user/.local/share/virtualenvs/kebechet-_898aJn5/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
[pipenv.exceptions.InstallError]:         _build_ext.run(self)
[pipenv.exceptions.InstallError]:       File "/usr/lib64/python3.8/distutils/command/build_ext.py", line 340, in run
[pipenv.exceptions.InstallError]:         self.build_extensions()
[pipenv.exceptions.InstallError]:       File "/tmp/pip-install-e6gaigrv/fasttext_5ef2bef9feac453c9ee1e45e65c18234/setup.py", line 146, in build_extensions
[pipenv.exceptions.InstallError]:         opts.append(cpp_flag(self.compiler))
[pipenv.exceptions.InstallError]:       File "/tmp/pip-install-e6gaigrv/fasttext_5ef2bef9feac453c9ee1e45e65c18234/setup.py", line 108, in cpp_flag
[pipenv.exceptions.InstallError]:         raise RuntimeError(
[pipenv.exceptions.InstallError]:     RuntimeError: Unsupported compiler -- at least C++0x support is needed!
[pipenv.exceptions.InstallError]:     ----------------------------------------
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: /home/user/.local/share/virtualenvs/kebechet-_898aJn5/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e6gaigrv/fasttext_5ef2bef9feac453c9ee1e45e65c18234/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e6gaigrv/fasttext_5ef2bef9feac453c9ee1e45e65c18234/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fg1u2kf0/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.local/share/virtualenvs/kebechet-_898aJn5/include/site/python3.8/fasttext Check the logs for full command output.
ERROR: Couldn't install package: fasttext
 Package installation failed...
```

**Comment by harshad16** [comment]
**Error 4**
```
inxcontrib-serializinghtml-1.1.5
+ [[ kebechet = \t\h\a\m\o\s ]]
+ pipenv run sphinx-apidoc -o docs/source thoth --implicit-namespaces
/home/user/clones/kebechet/thoth is not a directory.
```

**Comment by harshad16** [comment]
The issue is fixed and running successfully
https://github.com/thoth-station/thoth-station.github.io/commit/baab876908295e6f1480dc882629e51cf2db06dd

**Comment by fridex** [comment]
Thanks @harshad16 👍🏻 💯
